version: '3'
services:
    nginx:
        image: nginx:1.18
        volumes:
            - .:/var/www/app
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        ports:
            - 21080:80
    php:
        build: ./
        volumes:
            - ./:/var/www/app
            - ./docker/php/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
